#!/bin/bash
# SUPER SIMPLE COMMANDS - Copy Paste Karo!

echo "=== STEP 1: Make script executable (one time only) ==="
echo "chmod +x /www/wwwroot/RupiyaMe/dev-manager.sh"
echo ""
echo "=== Common Commands ==="
echo ""
echo "# Check status"
echo "/www/wwwroot/RupiyaMe/dev-manager.sh status"
echo ""
echo "# Start DEV environment (Testing)"
echo "/www/wwwroot/RupiyaMe/dev-manager.sh dev"
echo ""
echo "# Stop DEV environment"
echo "/www/wwwroot/RupiyaMe/dev-manager.sh stop-dev"
echo ""
echo "# View DEV logs"
echo "/www/wwwroot/RupiyaMe/dev-manager.sh logs dev"
echo ""
echo "# Deploy DEV to PRODUCTION (after testing)"
echo "/www/wwwroot/RupiyaMe/dev-manager.sh deploy"
echo ""
echo "=== Manual PM2 Commands ==="
echo ""
echo "# Start dev manually"
echo "cd /www/wwwroot/RupiyaMe && git checkout dev && pm2 start ecosystem.dev.config.js"
echo ""
echo "# Check all services"
echo "pm2 status"
echo ""
echo "# View logs"
echo "pm2 logs"
echo ""
echo "=== URLs ==="
echo "Production: http://your-ip:4521 (Port 8049 backend)"
echo "Development: http://your-ip:4522 (Port 8050 backend)"
